# Use postgres/example user/password credentials
version: '3.1'

services: 
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    networks:
      - confluent_default
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"  
networks:
  confluent_default:
    external: true